### ISSUE TITLE
Ultrasonic data  transmission via android 

### ISSUE THREAD

**Issue by i-rizwan** [beeping-io/beeping-examples#4]
Hi Team ,
I have gone through the repo's
all are nice
i am facing an issue,  i am trying to implement data Transmission from android to other device is there any doc for implementation data transmission.

**Comment by alfredrc** [comment]
Hello ! Of course ...

You can access from beeping.io ...

You have docs about how to implement.

On the other hand, you can access to our Slack Community from here: https://docs.beeping.io/community/

Let me know whether you need some help.
